### PR TITLE
refactor: make `toFlat` as utility

### PR DESCRIPTION
**Pull request by jsun969**
https://github.com/react-hook-form/devtools/pull/150#discussion_r917247375

### CODE REVIEW

**Comment by jsun969** [comment]
When I reinstall the packages, the editor said

image

Is it all good in your computer?

**Comment by jsun969** [comment]
And have you tried it in example?
Issue: #149

**Comment by bluebill1049** [comment]
> And have you tried it in example? Issue: #149

I haven't got a chance.

**Review by bluebill1049 — APPROVED** [review]

**Comment by jsun969** [comment]
> > And have you tried it in example? Issue: #149
> 
> I haven't got a chance.

kk. Maybe we have to fix that before release

**Pull request merged**
