### PR TITLE
Fix ssr when generate uuid

### LINKED ISSUE #161: Change the example to Nextjs
According to #156 #157, I assume we can change our `vite` example to `next.js`

### PR DESCRIPTION
**Pull request by jsun969**
resolve #161

### CODE REVIEW

**Comment by jsun969** [comment]
image

**Comment by jsun969** [comment]
I modified code to this. Vite example runs properly.
https://github.com/react-hook-form/devtools/pull/160#issuecomment-1183767644

But nextjs have an error, I don't know how to fix it...

image

We can replace the vite `/example` by `/nextjs-example` after we fix this.

**Comment by jsun969** [comment]
But ye... We can merge it first and create `4.2.2-beta.1`. The error only occured in example. But the main code works fine.

**Comment by bluebill1049** [comment]
instead of using nextJS maybe we can use vite with SSR, keep this repo simple, in fact, if this mismatch is resolved we probably don't have to worry about it too much by introducing SSR in this repo.

**Comment by jsun969** [comment]
I see

**Comment by bluebill1049** [comment]
the fix looks good have published the patch

**Pull request merged**
