### PR TITLE
Fix #153

### LINKED ISSUE #153: `control._names.mount` is undefined in example
Browser error:

image
image

Editor error:
image

### PR DESCRIPTION
**Pull request by jsun969**
fix #153

### CODE REVIEW

**Comment by jsun969** [comment]
I just improve the example.. but need your help @bluebill1049

**Comment by bluebill1049** [comment]
I am quite busy at the moment, I won't have time to look into this shortly.

**Comment by jsun969** [comment]
It's ok. I'll try to fix it
Don't stress about it xD

**Comment by bluebill1049** [comment]
thanks, @jsun969 for understanding sorry if I haven't got a chance to reply to your message or response.

**Comment by jsun969** [comment]
@Moshyfawn xD

**Comment by jsun969** [comment]
Sry, I just upgrade the rhf's version (both devtools and example to `7.33.1`) and everything is fine. lol
I think our chrome extension has totally done! 🎉 @bluebill1049 

cc @Moshyfawn

**Comment by bluebill1049** [comment]
That's awesome, would you be able to provide some screenshots for the extension, I have been busy but if you can provide some screenshots I can check the UI and give feedback if any.

**Comment by jsun969** [comment]
ye, sure!
sth error in the storybook. I may fix the type problem first xD

**Comment by jsun969** [comment]
image

**Comment by jsun969** [comment]
I've tweeted it
https://twitter.com/jsun969/status/1546340720378015745

**Comment by bluebill1049** [comment]
Looks awesome! I will find time to publish the chrome extension.

**Review by bluebill1049 — APPROVED** [review]
LGTM!

**Comment by jsun969** [comment]
thx. Can we publish this detools first?

**Comment by bluebill1049** [comment]
could you verify the beta version: `4.1.2-beta.0`?

**Comment by jsun969** [comment]
> could you verify the beta version: `4.1.2-beta.0`?

sure.. where to verify?

**Comment by bluebill1049** [comment]
in the example app use the beta version instead?

**Comment by jsun969** [comment]
I don't understand.. which example app you mean
can we move to wechat?

**Comment by bluebill1049** [comment]
i mean use this example: https://github.com/react-hook-form/devtools/blob/master/example/package.json install the beta version, see if it's working as expected.

**Comment by jsun969** [comment]
It don't need. I import it by folder
https://github.com/react-hook-form/devtools/blob/5cf4ada138295a8b50f50c2297ca0d4bcb59fd28/example/src/App.tsx#L1-L2

**Comment by jsun969** [comment]
image

I think it's no problem 👍

**Comment by jsun969** [comment]
lol! got it

**Pull request merged**
